export const styles = {
  statGrid: { display: 'grid', gridTemplateColumns: 'repeat(4,1fr)', gap: '10px', marginBottom: '16px' },
  statCard: { background: '#fff', border: '1px solid #E5E7EB', borderRadius: '8px', padding: '14px 16px' },
  statLabel: { fontSize: '11px', color: '#666', marginBottom: '6px' },
  statVal: { fontSize: '26px', fontWeight: '700' },
  panel: { background: '#fff', border: '1px solid #E5E7EB', borderRadius: '8px', marginBottom: '12px' },
  panelHead: { padding: '13px 18px', borderBottom: '1px solid #E5E7EB', display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  panelTitle: { fontSize: '13px', fontWeight: '600', color: '#111' },
  panelLink: { fontSize: '12px', color: '#185FA5' },
  empty: { padding: '24px', textAlign: 'center', color: '#aaa', margin: 0 },
  table: { width: '100%', borderCollapse: 'collapse', fontSize: '12px' },
  thead: { background: '#F9FAFB' },
  th: { padding: '9px 16px', textAlign: 'left', fontSize: '11px', fontWeight: '500', color: '#666', borderBottom: '1px solid #E5E7EB' },
  tr: { borderBottom: '1px solid #F3F4F6', cursor: 'default' },
  td: { padding: '10px 16px', color: '#111', verticalAlign: 'middle', textAlign: 'left' },
  meta: { fontSize: '11px', color: '#999' },
  btnGroup: { display: 'flex', gap: '6px' },
  btnApprove: { fontSize: '11px', padding: '4px 11px', borderRadius: '4px', cursor: 'pointer', background: '#EAF3DE', color: '#27500A', border: '1px solid #97C459', fontWeight: '500' },
  btnReject: { fontSize: '11px', padding: '4px 11px', borderRadius: '4px', cursor: 'pointer', background: '#FEE2E2', color: '#991B1B', border: '1px solid #FECACA', fontWeight: '500' },
  btnSecondary: { fontSize: '12px', padding: '7px 16px', borderRadius: '6px', cursor: 'pointer', background: '#F3F4F6', color: '#444', border: '1px solid #D1D5DB' },
  input: { padding: '8px 11px', fontSize: '13px', border: '1px solid #D1D5DB', borderRadius: '6px', width: '100%', boxSizing: 'border-box', marginBottom: '12px', outline: 'none' },
  errText: { fontSize: '12px', color: '#DC2626', margin: '4px 0 10px' },
  overlay: { position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.35)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 100 },
  modal: { background: '#fff', borderRadius: '10px', width: '100%', maxWidth: '460px', boxShadow: '0 20px 40px rgba(0,0,0,0.15)' },
  modalHead: { padding: '16px 20px', borderBottom: '1px solid #E5E7EB', display: 'flex', alignItems: 'center', justifyContent: 'space-between' },
  modalTitle: { fontSize: '14px', fontWeight: '600', color: '#111' },
  closeBtn: { background: 'none', border: 'none', cursor: 'pointer', fontSize: '14px', color: '#999' },
  modalBody: { padding: '20px' },
  modalBtns: { display: 'flex', gap: '8px', justifyContent: 'flex-end', marginTop: '16px' },
}